### PR TITLE
Destroy entity now destroys the whole hierarchy.

### PR DESCRIPTION
**Pull request by zaklaus**

### CODE REVIEW

**Comment by zaklaus** [comment]
Was implemented in 7469ab57f821a06f7a37916da3d6bdf15a52f882

**Comment by nem0** [comment]
Thanks, but like this it would break undo function. Instead it has to be done here https://github.com/nem0/LumixEngine/commit/7469ab57f821a06f7a37916da3d6bdf15a52f882

**Comment by nem0** [comment]
We can still have destroyEntityRecursive for use outside of editor == ingame

**Comment by zaklaus** [comment]
Oh I see, nice having it implemented now anyway.

**Pull request closed without merging**
