### PR TITLE
task: build genie before running it

### PR DESCRIPTION
**Pull request by dud3**
Would it make it better on linux? since the linux executable didn't work on my current ubuntu.

### CODE REVIEW

**Comment by dud3** [comment]
One thing to note, this time it needs `sudo`.

**Comment by nem0** [comment]
Do you by any chance have 32bit system?

**Comment by dud3** [comment]
Yes.

**Comment by dud3** [comment]
I think that would explain everything.

**Comment by nem0** [comment]
Yes, only 64bit is supported, I will add that to wiki

**Comment by dud3** [comment]
Great. I'm closing this pull request then.

**Comment by nem0** [comment]
It is possible to compile for 32bit systems, but you would have to recompile everything (genie, libraries in external/)

**Comment by dud3** [comment]
Indeed, thanks for letting me know, I'll switch to my 64bit computer in few days.

**Pull request closed without merging**
