### PR TITLE
Small editor changes

### PR DESCRIPTION
**Pull request by zaklaus**
Hi there,

I've recently found this and I must say I love the engine so far!

I would like to present some adjustments I made to make entity manipulation slightly better.
Editor is now able to duplicate entities and keep their original transformation based on the original version, created child of an entity should now also be located at (0,0,0) local position now.
There's also small possible bug fix when saving the universe would crash the editor. It could be because I have a slightly different workspace layout, but the fix should deal with such exceptions.

I will also create PR for that particular icon I made for "Duplicate entity" option [here](https://github.com/nem0/lumixengine_data/pull/109).

Thank you!
- Dominik.

### CODE REVIEW

**Comment by nem0** [comment]
Hi, you must have read my mind. I was thinking about this just yesterday when working on a game. 

One small issue, we can get rid of `setEntitiesLocalPositions` and use `setEntitiesPositions` with matching values

**Comment by zaklaus** [comment]
I will look at it now

**Comment by nem0** [comment]
I meant something a bit different :) but never mind, I can merge this and do it myself

**Comment by zaklaus** [comment]
Oh, I get it now. Well okay. :)

**Pull request merged**
